/* =============================================================================

	All bookmarks for Chet's News

============================================================================= */

import { NewsItem } from "./helpers/newsHelpers"

const news: Array<NewsItem> = []

news.push({
	date: 1486533645000,
	tags: [],
	title: "What Could Have Entered the Public Domain on January 1, 2017?",
	description:
		"All copyrights are set to expire at some point. 40 years ago in 1976 the expiration was extended from 56 years to 70 years. If that didn't happen, however, some pretty famous works from 1960 would become public domain.",
	url: "https://law.duke.edu/cspd/publicdomainday/2017/pre-1976/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Exploring Emergence",
	description:
		"An amazing interactive explanation of Conway's game of Life exploring emergence.",
	url: "http://www.playfulinvention.com/emergence/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Mastering Programming",
	description:
		"Interesting observations about the ways great programmers work.",
	url:
		"https://www.prod.facebook.com/notes/kent-beck/mastering-programming/1184427814923414",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Horrifying PDF Experiments",
	description:
		"Little did I know, you can write breakout inside a pdf document!",
	url: "https://github.com/osnr/horrifying-pdf-experiments",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Scrubbing Calculator",
	description:
		"Brett Victor explores interactive math with the scrubbing calculator.",
	url: "http://worrydream.com/ScrubbingCalculator/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Rainforest on Shadertoy",
	description:
		"An amazing procedural rendering in just under 1000 lines of code. No images, no external assets. Just code. Phenomenal.",
	url: "https://www.shadertoy.com/view/4ttSWf",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Eve - Quick Start Tutorial",
	description:
		"Eve is a new paradigm in the way we program. It's very ambitious and has some really cool ideas behind it. You can think of it as a more powerful version of Excel. And since the entire language is referentially transparent, I'm sure there are going to be an amazing set of tools for visualizing what you code in real time.",
	url: "http://play.witheve.com/#/examples/quickstart.eve",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Google AI invents its own cryptographic algorithm",
	description:
		"It's unlikely that the cryptography generated by these neural networks is going to better than AES, but its a elegant demonstration of adversarial optimization.",
	url:
		"https://arstechnica.co.uk/information-technology/2016/10/google-ai-neural-network-cryptography/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Wolfram Research Keynote 2016",
	description:
		"Mathematica is one of the most mind-blowing pieces of technology I've ever seen and it's only getting better. This year they added curated data sets for human anatomy, food, historical empires, yoga poses, and much more.",
	url:
		"https://www.youtube.com/watch?v=0d1O5DWOP0E&index=1&list=PLxn-kpJHbPx25SgGxHwkL5Bt9lWlyCEUo",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "ElixirConf Keynote 2016",
	description:
		"Jose Valim demonstrates how easy it is to lazily distribute computation in Elixir since it baked right into the language.",
	url: "https://www.youtube.com/watch?v=srtMWzyqdp8",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Writing efficient JavaScript",
	description:
		"It's interesting to see all of the tiny optimizations in JavaScript. Subtle things like `if (something === true)` rather than `if (something)`.",
	url:
		"https://medium.com/@xilefmai/efficient-javascript-14a11651d563#.ex7odc36a",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Testing the way it should be",
	description:
		"Cypress is an amazing new JavaScript testing framework that gives you headless browser testing without Selenium or PhantomJS, access to the state of the browser, and amazing replay capabilities.",
	url: "https://www.youtube.com/watch?v=lK_ihqnQQEM",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The Universality of Static Sites",
	description:
		"The trade-off between client-side web apps and server rendered websites doesn't have to be so black-and-white. Using some new Webpack tools, you can generate static HTML at compile-time.",
	url: "https://www.youtube.com/watch?v=ovIrOMBbWrc",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Markdown + React = 💙",
	description:
		"Markdown can be a lot more extensible than you might think. This talk shows you how to create markdown tags that render React components!",
	url: "https://www.youtube.com/watch?v=MM0XgD89Tr8",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "EC2 Instances (F1) with Programmable Hardware",
	description:
		"AWS now offers FPGA instances along with a marketplace. This is big deal in the world of machine learning and data processing.",
	url:
		"https://aws.amazon.com/blogs/aws/developer-preview-ec2-instances-f1-with-programmable-hardware/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Exceptional results: Error handling with C# and Rust",
	description:
		"This is a great introduction into monadic error handling and one of the many reasons people are flocking to Rust.",
	url:
		"https://ruudvanasseldonk.com/2015/06/17/exceptional-results-error-handling-in-csharp-and-rust",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Zero-cost abstractions",
	description:
		"Rust comes loaded with language features that elegantly compile into performant low-level instructions.",
	url: "https://ruudvanasseldonk.com/2016/11/30/zero-cost-abstractions",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "A Javascript journey with only six characters",
	description:
		"An explanation of the JSFuck library allowing you to write Turing Complete JavaScript with only 6 characters []()!+ More than anything, it demonstrates the challenge of keeping malware out of internet advertisements.",
	url:
		"https://web.archive.org/web/20161011071742/http://www.jazcash.com/a-javascript-journey-with-only-six-characters/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Anamorphisms in JavaScript",
	description:
		"This is an amazing introduction to some category theory concepts in JavaScript. In this post you'll learn about fold and unfold, and how to use these abstractions to trivially build breadth-first or depth-first traversals of a tree.",
	url: "http://raganwald.com/2016/11/30/anamorphisms-in-javascript.html",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Building offline-first Progressive Web Apps",
	description:
		'Keynote talk at Google I/O 2016 demonstrates some of the latest features in Google Chrome like Service Workers and IndexedDb to build a "progressive" chat application that works offline.',
	url: "https://www.youtube.com/watch?v=cmGr0RszHc8&feature=share",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Why Kakoune - The quest for a better code editor",
	description:
		"Kakoune is reinventing modal code editing and has some really features that improve on Vim.",
	url: "http://kakoune.org/why-kakoune/why-kakoune.html",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Professor Frisby Introduces Composable Functional JavaScript",
	description:
		"Brian Lonsdorf always has the most amazing functional programming resources that are consumable for the average JavaScript developer. This Egghead series is amazing.",
	url:
		"https://egghead.io/courses/professor-frisby-introduces-composable-functional-javascript",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Idealized Commit Logs: Code Simplification via Program Slicing",
	description:
		'Very interesting talk about "code slicing" using unit tests with code coverage reporting to make it easier to read and understand how code works.',
	url: "https://www.youtube.com/watch?v=dSqLt8BgbRQ",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Building OSX Apps with JavaScript",
	description:
		"This article explores the new MacOS JavaScript bridge. It's not very well documented, but allows you to access native libraries using JavaScript. I'd imagine we're going to see some really cool NPM packages coming out soon.",
	url: "https://tylergaw.com/articles/building-osx-apps-with-js",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "LibreTaxi - free and open source Uber/Lyft alternative",
	description:
		"An open source ride sharing application that you interact with through a Telegram chat bot -- very cool. Pretty much every application can be reimagined as a chat bot and the benefit of using a chat bot is a much lower barrier to entry to build a product. You don't need to build your own frontend application for every platform, and you don't need to integrate your own payment systems. ",
	url: "http://libretaxi.org/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The History and Evolution of Computer Viruses",
	description:
		"A comprehensive history of computer viruses from DEFCON 19 (2011).",
	url: "https://www.youtube.com/watch?v=yswPIwDFYDY",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Circles Sines and Signals",
	description:
		"An awesome interactive introduction to discrete signal processing.",
	url: "http://jackschaedler.github.io/circles-sines-signals/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Explorable Explanations",
	description:
		"Brett Victor explains a better world in which explanations are interactive and explorable.",
	url: "http://worrydream.com/ExplorableExplanations/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Media for Thinking the Unthinkable",
	description:
		"Brett Victor's talk at the MIT Media Lab about software that augments human intelligence.",
	url: "https://vimeo.com/67076984",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Transit Maps: Apple vs. Google vs. Transit",
	description:
		"A great article about some of the thoughtful design that went into the Transit app as compared to Apple and Google maps.",
	url:
		"https://medium.com/transit-app/transit-maps-apple-vs-google-vs-us-cb3d7cd2c362#.jwymd6awd",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Dark Patterns - User Interfaces Designed to Trick People",
	description:
		"This is an amazing talk demonstrating objectively evil and deceptive designs from many well known companies. I whole heartedly agree with his message of shaming these businesses into behaving well.",
	url: "http://darkpatterns.org/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Archipelago and Atomic Communitarianism",
	description:
		'A thorough breakdown of Liberalism, the contradictions of modern "liberal" perspectives, problems with strict liberalism, and what a hypothetical liberal utopia might look like.',
	url:
		"http://slatestarcodex.com/2014/06/07/archipelago-and-atomic-communitarianism/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Facebook fake-news writer",
	description:
		"An interview with a guy who writes fake news that's been fooling lots of people. I think it uniquely highlights the dichotomy that has arisen from technology bringing about \"freedom of information\" in today's world world.",
	url:
		"https://www.washingtonpost.com/news/the-intersect/wp/2016/11/17/facebook-fake-news-writer-i-think-donald-trump-is-in-the-white-house-because-of-me/?tid=sm_tw&utm_term=.d9e70be72b5e",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Parable of the Polygons",
	description:
		"An enlightening interactive essay explaining the dynamics of segregation in society.",
	url: "http://ncase.me/polygons/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Groove Pizza",
	description:
		"Interesting drum beat maker using Tone.js with a unique visualization that lays a sequencer on a circle with shapes to indicate the rhythm of each track.",
	url: "https://apps.musedlab.org/groovepizza/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Yaybahar by Görkem Şen",
	description:
		"An entirely acoustic instrument that makes some incredible sounds.",
	url: "https://www.youtube.com/watch?v=_aY6TxC1ojA",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Still File",
	description: "Some amazing photographs recreating computer generated images.",
	url: "http://skrekkogle.com/still-file/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Recode Replay",
	description: "An awesome podcast of interviews with CEOs and world leaders.",
	url: "http://www.recode.net/recode-replay-podcast",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "David Attenborough's Rise of Animals",
	description:
		"David Attenborough walks you through the biological origins of animals, inspecting ancient fossils and explaining the evolutionary leaps from one species to the next. Watch it on Netflix!",
	url: "http://www.riseofanimals.com/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The mind behind Linux",
	description:
		"A casual interview with Linus Torvalds. Nothing too exciting, but an interesting insight into the life of a random geek who changed the world in a huge way.",
	url: "https://www.youtube.com/watch?v=o8NPllzkFhE",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The Untold History of the United States",
	description:
		"Oliver Stone's amazing TV series about the history of the US with a meticulous attention to the details.",
	url: "http://www.imdb.com/title/tt1494191/",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The Epic Guide to Bootstrapping a SaaS Startup from Scratch",
	description:
		'A no-bullshit article that\'s a little coarse, but possibly just the right motivation you need to get you SaaS startup off the ground. Probably the most valuable thing I got out of this article is this fill-in-the-blank exercise: "I believe that people want to <ability> so that they can <outcome>, and they would pay good money for that because <value>."',
	url:
		"https://medium.com/@cliffordoravec/the-epic-guide-to-bootstrapping-a-saas-startup-from-scratch-by-yourself-part-1-4d834e1df8c1#.u54ejph54",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "Facebook Reports Third Quarter 2016 Results",
	description:
		"Facebook just released an insanely impressive earnings report. Since last year, their revenue has increased 56% and their profit has increased 166%. That's nuts for a company of their size.",
	url:
		"https://investor.fb.com/investor-news/press-release-details/2016/Facebook-Reports-Third-Quarter-2016-Results/default.aspx",
})

news.push({
	date: 1486533645000,
	tags: [],
	title: "The Real Reason Your City Has No Money",
	description:
		"An interesting article about how federal stimulus incentives have crippled cities with debt by overdeveloping infrastructure.",
	url:
		"https://www.strongtowns.org/journal/2017/1/9/the-real-reason-your-city-has-no-money",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "The Idea of Lisp",
	description:
		"An enlightening essay about the origins of Lisp revealing its simplicity and elegance.",
	url: "https://dev.to/ericnormand/the-idea-of-lisp",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "The Future of Programming",
	description:
		"Brett Victor gives talk set in 1973 about some of the cutting edge research in programming and computer science. He makes some predictions about the future of programming, and leaves you feeling like we've fallen short.",
	url: "https://www.youtube.com/watch?v=8pTEmbeENF4",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Stop Drawing Dead Fish",
	description:
		"Brett Victor explores the shortcomings of digital art with an amazing tool for creating interactive art using geometric user interface representations rather than algebraic code. ",
	url: "https://www.youtube.com/watch?v=ZfytHvgHybA",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Mnemonist",
	description:
		"A curated collection of data structures for JavaScript like the Burkhard-Keller Tree for efficiently fuzzy-matching text!",
	url:
		"https://yomguithereal.github.io/mnemonist/?utm_source=javascriptweekly&utm_medium=email",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Social Infrastructure",
	description:
		"A great ted talk about architecture. At 14:40, there's a particularly incredible project designing a powerplant that turns garbage into energy, has a ski slope the length of two olympic halfpipes, has 300ft (largest in the world) continuous climbing wall, and blows rings with the steam accumulated from generating power.",
	url: "https://www.youtube.com/watch?v=8PItGf69eaw&feature=youtu.be&t=14m40s",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "How not to be ignorant about the world",
	description:
		"A TED talk explaining biases in our thinking that lead us to having entirely misconceived and often pessimistic notions about the world. RIP Has Rosling who died this past week.",
	url: "https://www.youtube.com/watch?v=Sm5xF-UYgdg",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Peter Thiel, Trump’s Tech Pal, Explains Himself",
	description:
		"An interesting interview with Peter Theil about his perspectives on President Trump and the Republican party. Whether or not you agree with him, the guy knows what he's talking about.",
	url:
		"https://www.nytimes.com/2017/01/11/fashion/peter-thiel-donald-trump-silicon-valley-technology-gawker.html?_r=0",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Free Parking Comes at a Price",
	description:
		"This article highlights the shortsightedness that often makes me skeptical of politics where something seemingly harmless and beneficial, like free parking, can have adverse effects and unintended consequences. ",
	url: "https://mobile.nytimes.com/2010/08/15/business/economy/15view.html",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "Valve Employee Handbook",
	description:
		"Valve is a huge videogame company that has an entirely flat organization structure. This document outlines the way their company works and its quite interesting. Not to mention its written as you might expect from a videogame company.",
	url: "http://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf",
})

news.push({
	date: 1487033249000,
	tags: [],
	title: "How to build a better block",
	description:
		"An amazing story about a guy and his friends who took matters into their own hands and revitalized a small town outside of Dallas.",
	url: "https://www.youtube.com/watch?v=ntwqVDzdqAU",
})

news.push({
	date: 1487033249000,
	tags: [],
	title:
		"Robin Abad Ocubillo, Urban Designer, San Francisco Planning Department",
	description:
		'An interesting talk about urban design and San Francisco\'s "parklet" program. Check out the [Parklet Manual](http://pavementtoparks.org/wp-content/uploads//2015/12/SF_P2P_Parklet_Manual_2.2_FULL1.pdf) as well.',
	url: "https://www.youtube.com/watch?v=9zYcJgmjQsk",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Inventing on Principle",
	description:
		"Brett Victor gives an inspiring talk that transcends technology and talks more about purpose in life. Dedicating your life to a guiding principle can go beyond social causes and still have a huge impact on the world.",
	url: "https://www.youtube.com/watch?v=PUv66718DII",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "The Birth & Death of JavaScript",
	description:
		"A futuristic talk recollecting on JavaScript and web assembly as the birth of a new platform for building software. There are some incredible demos of using WASM to compile applications like GIMP into JavaScript and run in the browser.",
	url:
		"https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Detour",
	description:
		"An app with curated immersive audio walking tours with amazing narrators and stories.",
	url: "https://www.detour.com/",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Scrape data from any website in minutes with ParseHub",
	description:
		"Pretty sweet website for interactively setting up web scrapers. Seems to be very robust and well-made. Not sure how it compared with [Kimono Labs](https://www.kimonolabs.com/) or [Import IO](https://www.import.io/) though.",
	url: "https://www.parsehub.com/",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Notion",
	description:
		"A neat platform for writing, publishing, and organizing thoughts.",
	url: "https://www.notion.so/invite/link/9a51f675e1e246e58bcd6bc535c7e7cb",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Airtable",
	description:
		"A powerful and flexible tool that combines Excel with a full-fledged CMS. Make sure you check out their [12 minute video guide](https://vimeo.com/165624533/472b9dcc9c) through all of their features -- its very impressive!",
	url: "https://airtable.com/invite/r/G9xora2T",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Quip",
	description: "Another interesting Google Docs competitor.",
	url: "https://quip.com/",
})

news.push({
	date: 1487592000000,
	tags: [],
	title: "Tactical Urbanism by The Street Plans Collaborative",
	description:
		"Cool little book about taking urban planning into your own hands. I'm so down to go chair bombing in the summer.",
	url:
		"https://issuu.com/streetplanscollaborative/docs/tactical_urbanism_vol_2_final?mode=window&backgroundColor=%23222222",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Ably Apparel",
	description:
		"A clothing brand selling clothes with a super-hydrophobic coating.",
	url: "https://ablyapparel.com/",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Clara - a virtual employee that schedules your meetings.",
	description:
		"Cool idea of a virtual assistant that schedule meetings for you over email",
	url: "https://claralabs.com/",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Using ClojureScript w/ Heavy Industrial Equipment",
	description:
		"This talk isn't actually as technical as you might think. If you're a project manager and write specs all day, I'd recommend watching 5:00 - 20:00 where he talks about Harel Statecharts. I personally hate reading specs and find them terribly hard to consume. If you dig the talk, check out [Harel's paper](http://www.inf.ed.ac.uk/teaching/courses/seoc/2005_2006/resources/statecharts.pdf) he wrote about it back in 1987.",
	url: "https://www.youtube.com/watch?v=S2-EYSeWaPg",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Polestar",
	description:
		"An awesome tool for rapidly exploring and building data visualizations. It uses [vega](https://vega.github.io/) which is a declarative JSON syntax for defining visualizations that's actually built on the amazing [d3](https://d3js.org/) library. ",
	url: "http://vega.github.io/polestar/",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "The Mother of all Demos",
	description:
		"Doug Engelbart invented the computer mouse, text processing, and many other staples of the modern computer. He demoed all of this in 1968 in what is considered the greatest demo of cutting technology.",
	url: "https://www.youtube.com/watch?v=1U-b7lxG_z8",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Type-driven Development with Idris",
	description:
		"Not the most entertaining talk, but still an incredible interesting and innovative demo. Idris is a very academic language built for theorem proving, and this demo shows how you can define the type signature of a function and let the theorem prover write code for you!",
	url: "https://www.youtube.com/watch?v=gonVdPyVwQQ&feature=youtu.be&t=16m55s",
})

news.push({
	date: 1488196800000,
	tags: [],
	title:
		"Don't Dismiss President Trump's Attacks on the Media as Mere Stupidity",
	description:
		'An interesting article about recent events and how Trump\'s stupidity could actually be a strategy that happens to be working. My favorite quote from this article that sums things up is: "Outrage will fall victim to its own ubiquity."',
	url: "http://time.com/4675860/donald-trump-fake-news-attacks/",
})

news.push({
	date: 1488196800000,
	tags: [],
	title: "Against Bravery Debates",
	description:
		"An interesting analysis of a common tendency to feel as if you are bravely standing up against the establishment. Basically, this is why I can't stand watching the news anymore.",
	url: "https://slatestarcodex.com/2013/05/18/against-bravery-debates/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title:
		"SpaceX to Send Privately Crewed Dragon Spacecraft Beyond the Moon Next Year",
	description:
		"SpaceX is starting to make bigger moves, launching two private citizens further into space than ever before (beyond the moon)! Exciting stuff.",
	url:
		"http://www.spacex.com/news/2017/02/27/spacex-send-privately-crewed-dragon-spacecraft-beyond-moon-next-year",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "The Mercury logic programming system.",
	description:
		"A state-of-the-art logic programming language that's fast and statically typed!",
	url: "https://github.com/Mercury-Language/mercury",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Normal Considered Harmful",
	description:
		"An inspirational talk by Alan Kay about the stagnation of ground-breaking ideas.",
	url: "https://www.youtube.com/watch?v=FvmTSpJU-Xc",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Blockspring",
	description:
		"A plugin for Google Sheets that scrapes and curates data across the web.",
	url: "https://www.blockspring.com/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Introduction to Parsers",
	description:
		"I deep-dive into building parsers with a nice introduction to linguistics written by yours truly.",
	url:
		"https://medium.com/@chetcorcos/introduction-to-parsers-644d1b5d7f3d#.q2bo3047f",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Flowhub visual programming",
	description:
		"A visual-based programming environment right in your browser using [NoFlo](https://noflojs.org). It's a very cool idea, but the experience isn't quite there yet. Check out [this WebAudio demo](http://app.flowhub.io/#example/04847249319d2326fa92) to get a feel for it.",
	url: "https://flowhub.io",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Framer",
	description:
		"A powerful web design tool that writes code for you to build interactive experiences.",
	url: "https://framer.com/features/overview/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Canvas",
	description:
		"A nicely designed minimalist collaborative Markdown editing tool. Check out [their video guide](https://vimeo.com/154083630).",
	url: "https://usecanvas.com/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Figma: the collaborative interface design tool.",
	description:
		"Another cool we design tool, but this one is collaborative in the browser!",
	url: "https://www.figma.com/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "Webflow",
	description:
		"A web design tool backed by a built-in CMS and hosting solution. Its perfect for setting up a custom blog, but falls short of a general-purpose tool.",
	url: "https://webflow.com/",
})

news.push({
	date: 1488826311000,
	tags: [],
	title: "WINGiT",
	description:
		"Another attempt at an event discovery platform. Reminds me of when I built the [Shindig app](https://medium.com/@chetcorcos/shindig-an-event-discovery-app-built-with-meteor-js-react-js-and-neo4j-602afb483ae6#.q32aactbk). The big problem in this space is the lack of curation.",
	url: "http://www.thewingitapp.com/en",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "WikiLeaks Vault7",
	description:
		"If you haven't heard by now, WikiLeaks released a ton of CIA exploits and information about the CIA's massive hacking operation. It's going to be fun to see all the software patches that come out in the coming weeks. [Notepad++](https://notepad-plus-plus.org/news/notepad-7.3.3-fix-cia-hacking-issue.html) already got one patch in.",
	url: "https://wikileaks.org/ciav7p1/",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Descript audio word processing",
	description: "An impressive tool built by Detour for creating tour guides.",
	url: "https://www.youtube.com/watch?v=1evmLntTT20",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "A Brief History of Random Numbers",
	description:
		"I've always been curious about how computers generate random numbers, and this article gives a great introduction.",
	url:
		"https://medium.com/@tashian/a-brief-history-of-random-numbers-9498737f5b6c#.2xkeeok5q",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Who Can Name the Bigger Number?",
	description:
		"A mathematician explores the extremes of mathematical notion for expression really large numbers. It's a bit long, but starts to get really interesting about half way through when he starts talking about Turing machines and *busy beaver* numbers.",
	url: "http://www.scottaaronson.com/writings/bignumbers.html",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Alexander Shulgin",
	description:
		'A fascinating chemist responsible for developing hundreds of psychedelic drugs with a "schedule 1 license" from the DEA for pharmacology research.',
	url: "https://en.wikipedia.org/wiki/Alexander_Shulgin",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Better Automata Through Combinators",
	description:
		"A clever library for building finite-automata using functional combinators.",
	url: "https://github.com/ztellman/automat",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Build a digital clock in Conway's Game of Life",
	description:
		"Crazy implementation of a digital clock in Conway's Game of Life. Run it yourself [here](https://copy.sh/life/?gist=f3413564b1fa9c69f2bad4b0400b8090&step=512). If you don't know Conway's Game of Life, you can learn more about it [here](http://www.playfulinvention.com/emergence/).",
	url:
		"http://codegolf.stackexchange.com/questions/88783/build-a-digital-clock-in-conways-game-of-life/",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Seeing Theory",
	description:
		"Interactive animations for learning probability theory concepts.",
	url: "http://students.brown.edu/seeing-theory/",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Room 641A",
	description:
		"Just a sketchy room located next door to Affirm (where I used to work) at 611 Folsom St. where the NSA taps all communications that travel overseas. ",
	url: "https://en.wikipedia.org/wiki/Room_641A",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "Simpson's Paradox",
	description:
		"Simpson's paradox is a really simple and unintuitive example of why you should always be skeptical of statistics. It's just a special case of omitted variable bias. [This is another good example from this Civil Right Act](http://michaelnielsen.org/reinventing_explanation/). ",
	url: "http://vudlab.com/simpsons/",
})

news.push({
	date: 1489402800000,
	tags: [],
	title: "The History of the International Diamond Cartel",
	description:
		"An interesting paper about the secretive diamond industry led by a Central Selling Organization that hordes diamonds, controlling supply and artificially inflating prices.",
	url: "http://pages.stern.nyu.edu/~lcabral/teaching/debeers3.pdf",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Fractal Lab 2015 Demo",
	description:
		"This 3D fractal explorer is one of the most amazing pieces of software I've ever seen.",
	url: "https://vimeo.com/126664436",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Recursive Drawing",
	description: "A recursive drawing interface for building fractals!",
	url: "http://recursivedrawing.com/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Apparatus",
	description:
		"A hybrid graphics editor and programming environment for creating interactive diagrams with a very impressive user interface. [Play with it yourself!](http://aprt.us/editor/)",
	url: "http://aprt.us/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Shadershop",
	description:
		"A graphical user interface for building GLSL shaders without writing code. Also an interesting visual tutorial on how to create pseudorandom noise. [Try it out yourself!](http://www.cdglabs.org/Shadershop/)",
	url: "http://tobyschachman.com/Shadershop/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "GLSL Eye Ball Tutorial",
	description:
		"An impressive tutorial on how to create an eye ball using GLSL procedural generation. This guy has insane skills. He also built [ShaderToy](https://www.shadertoy.com/) which has a bunch of cool demos.",
	url: "https://www.youtube.com/watch?v=emjuqqyq_qc",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "GPU Sound Tutorial",
	description:
		"A tutorial on procedurally generated sound using the GPU just like a GLSL shaders. You can play around with your own sounds with [SoundToy](http://www.iquilezles.org/apps/soundtoy/index.html). ",
	url: "https://www.youtube.com/watch?v=ogFAHvYatWs",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Glitch",
	description:
		"A collaborative IDE for building websites and reusing code from other Glitch projects.",
	url: "https://glitch.com/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Martian Math",
	description:
		"I built an interactive diagram using Apparatus to explain one of my favorite riddles!",
	url: "https://medium.com/@chetcorcos/martian-math-812a029e2ea0#.tsso981ck",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Origami Studio",
	description: "A visual programming tool for designers built by Facebook.",
	url: "http://origami.design/tutorials/getting-started/Getting-Started.html",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Snarky Puppy - We Like It Here",
	description: "This entire live performance album is amazing.",
	url: "https://www.youtube.com/watch?v=L_XJ_s5IsQc&list=RDL_XJ_s5IsQc#t=0",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "ByteBeat: one-line music programs",
	description:
		"Creating musical melodies using simple C expressions with bitwise logic. [Try it out yourself!](http://greggman.com/downloads/examples/html5bytebeat/html5bytebeat.html#t=0&e=0&s=8000&bb=5d000001000a00000000000000003a0800c218d17457ec97b405f8dffff4a92000)",
	url:
		"http://countercomplex.blogspot.com/2011/10/some-deep-analysis-of-one-line-music.html",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Drips",
	description: "A cool little art project for drawing colorful water drips.",
	url: "https://simonlast.org/archive/drips/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Refractor",
	description:
		"An application for creating fractals by composing GLSL shader functions with an awesome multi-touch interface.",
	url: "http://refractor.pixelshaders.com/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "Twine",
	description:
		"An open-source tool for telling interactive, nonlinear stories.",
	url: "http://twinery.org/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "p5.js",
	description:
		"An awesome library, inspired by Processing, for building interactive visualizations and art projects on the web.",
	url: "http://p5js.org/",
})

news.push({
	date: 1490041278000,
	tags: [],
	title: "RescueTime",
	description:
		"Really simple time-management software that tracks what applications you are using and provides you with analytics and dashboards to help you stay productive.",
	url: "https://www.rescuetime.com/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Bus Bunching Explained Visually",
	description:
		"Another cool explorable explanation demonstrating how buses tend to bunch together.",
	url: "http://setosa.io/bus/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "One second code",
	description: "Do you know how much your computer can do in a second? ",
	url: "http://computers-are-fast.github.io/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "How to Make Hydraulic Powered Robotic Arm from Cardboard",
	description: "Really cool project with cardboard and syringes. ",
	url: "https://www.youtube.com/watch?v=P2r9U4wkjcc",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "HakShop by Hak5",
	description:
		"If you've ever wondered where all those little hacking USB drives in the movies come from, look no further.",
	url: "https://hakshop.com/products/bash-bunny",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Time Machine style backup with Rsync",
	description:
		"The only software you need to backup your computer is rsync. This project mimics Time Machine by saving each back up to a new timestamped folder but saves memory by hard-linking all duplicate files to their previous backups.",
	url: "https://github.com/laurent22/rsync-time-backup",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Earth Primer",
	description:
		"If you have an iPad, download this app. Its an amazing interactive simulation of weather that feels like a game but it's actually an educational app.",
	url: "http://www.earthprimer.com/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Elements by Euclid",
	description:
		"The first six books of the Euclid's *Elements* published in 300BC about geometry where coloured diagrams and symbols are used instead of letters.",
	url: "https://archive.org/details/firstsixbooksofe00eucl",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Visualizing Algorithms",
	description:
		"The creator of [d3.js](https://github.com/d3/d3/wiki/Gallery) created some interactive visualizations of various algorithms like different ways of sampling, sorting, and maze solving.",
	url: "https://bost.ocks.org/mike/algorithms/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Mathigon - World of Mathematics",
	description: "An interactive math textbook.",
	url: "http://world.mathigon.org/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Immersive Linear Algebra",
	description: "An interactive textbook explaining linear algebra.",
	url: "http://immersivemath.com/ila/learnmore.html",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "How to Fold a Julia Fractal",
	description: "A very nice introduction to complex numbers and fractals.",
	url: "http://acko.net/blog/how-to-fold-a-julia-fractal/",
})

news.push({
	date: 1491217200000,
	tags: [],
	title: "Prototypo",
	description: "An open source tool for designing your own typography!",
	url: "https://www.prototypo.io/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "MarkSheet",
	description:
		"A very well designed free tutorial series on building websites starting with the basics.",
	url: "http://marksheet.io/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Flyboard Air",
	description: "Closest thing out there to a real jetpack.",
	url: "https://flyboard.com/flyboardair",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "The Boring Company",
	description:
		"Elon Musk's next project appears to be building tunnels under LA so he doesn't have to sit in traffic anymore.",
	url: "https://boringcompany.com/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "TodoMVC for the RealWorld™",
	description:
		'Examples of "real world" applications build with a variety of technology stacks.',
	url: "https://github.com/gothinkster/realworld",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Subtext: Two-way Dataflow",
	description:
		"A very cool demo of a visual programming language called Subtext.",
	url: "https://vimeo.com/106073134",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Hypercard",
	description:
		"Hypercard was a visual programming tool built at Apple in 1987 for organizing and automating everything you do on your computer.",
	url: "https://www.youtube.com/watch?v=EMFscTOazS0",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Audulus",
	description:
		"A visual programming language, similar to [Max MSP](https://cycling74.com/products/max/), for creating music. It has a really cool UI that works across all platforms.",
	url: "http://audulus.com/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "No ifs, ands, or buts",
	description:
		'Another version of Subtext that demonstrates how "good notation is half the problem".',
	url: "https://vimeo.com/140738254",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Argument Analysis Platform",
	description:
		"An interesting idea providing a nice UX for online discourse. I'm not sure it will ever work, but its a cool idea!",
	url: "http://en.arguman.org/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Teenage Engineering",
	description:
		"An interesting company with a range of well-designed and creative musical hardware products.",
	url: "https://www.teenageengineering.com/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "When Pixels Collide",
	description: "An awesome narrative about Reddit's r/Place experiment.",
	url: "http://sudoscript.com/reddit-place/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "Unlimited Pliability",
	description: "A really cool project made with a solenoid and a strobe light.",
	url: "https://presence-presents.myshopify.com/",
})

news.push({
	date: 1494105942000,
	tags: [],
	title: "The Get Down",
	description:
		"A show based on a true story about the birth of hip-hop in the 70s in the Bronx. Netflix as an interesting [documentary series on the same topic](https://www.netflix.com/title/80141782) as well.",
	url: "https://www.netflix.com/title/80025601",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Public JSON APIs",
	description: "A curated list of public JSON APIs for your projects",
	url: "https://github.com/toddmotto/public-apis",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "4D Toys",
	description: "A toy box full of 4 dimensional shapes!",
	url:
		"http://marctenbosch.com/news/2017/06/4d-toys-a-box-of-four-dimensional-toys/",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Graphcool - Serverless GraphQL Backend",
	description:
		"A promising Software-As-A-Service company that manages an entire GraphQL backend for you.",
	url: "https://www.graph.cool/",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Visual History",
	description: "An awesome way of visualizing your browsing history!",
	url:
		"https://chrome.google.com/webstore/detail/visual-history/nkckokcpjekkokllfplejfkocaikmnml/related",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "The greatest machine that never was",
	description:
		"An interesting tale about Charles Babbage who designed a Turing Complete mechanical computer in 1830.",
	url: "https://www.youtube.com/watch?v=FlfChYGv3Z4",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Steve Jobs unveils the Think Different campaign (1997)",
	description:
		"Apple's \"Think Different\" marketing campaign was unlike any other. It's very interesting to hear him talk though his thought-process and how Nike has never really advertises their sell shoes in their commercials .",
	url: "https://www.youtube.com/watch?v=4HsGAc0_Y5c",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Learning Music",
	description:
		"An interactive tutorial on learning and creating music, built by Ableton.",
	url: "https://learningmusic.ableton.com/index.html",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Helio Workstation",
	description:
		"A beautiful open source music sequencer with a an interesting UX for writing classical music based on intervals. ",
	url: "https://helioworkstation.com/",
})

news.push({
	date: 1497212355000,
	tags: [],
	title: "Oscilloscope Music",
	description:
		"This guy wrote an incredible album on an oscilloscope! This is a [great introductory video](https://www.youtube.com/watch?v=rtR63-ecUNo) to show you how the visualization works, and he also has a [more in-depth tutorial](https://www.kickstarter.com/blog/the-process-oscilloscope-music) on how to make your own oscilloscope music.",
	url: "http://oscilloscopemusic.com/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "What is Ethereum?",
	description:
		'A comprehensive overview of Ethereum -- a blockchain technology for Turing complete programs called "smart contracts". ',
	url: "https://blockgeeks.com/guides/what-is-ethereum/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Truffle Box React",
	description: "A simple full-stack Ethereum application starter project.",
	url: "https://github.com/truffle-box/truffle-box-react",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "HTML5 UP",
	description:
		"Free and open source responsive website designs, perfect for your next block or homepage!",
	url: "https://html5up.net/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "DEVCON1: Ethereum for Dummies",
	description:
		"Gavin Wood, co-founder of Ethereum, gives a high-level talk about the goals and aspirations of Ethereum.",
	url: "https://www.youtube.com/watch?v=U_LK0t_qaPo",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "DEVCON2: Ethereum in 25 Minutes",
	description:
		"Vitalik Buterin, co-founder of Ethereum, gives a technical overview of how Ethereum works.",
	url: "https://www.youtube.com/watch?v=66SaEDzlmP4",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Blocks",
	description: "A 3D VR CAD program build by Google.",
	url: "https://vr.google.com/blocks/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "What is an ICO (Initial Coin Offering) and How Does it Work?",
	description: "A decent explanation of initial coin offerings on Ethereum.",
	url:
		"https://www.fxempire.com/education/article/ico-initial-coin-offering-work-418446",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Paul Walker Video FX in Furious 7",
	description: "It seems that actors may continue acting well after they pass.",
	url: "https://www.youtube.com/watch?v=NbT93SoFkrw",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Magenta",
	description:
		"An interesting curation of blog articles applying machine learning to art and music.",
	url: "https://magenta.tensorflow.org/blog/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "How to create a cryptocurrency contract in Ethereum",
	description:
		"A relatively simple tutorial that shows you how to create a simple cryptocurrency on the Ethereum blockchain. Next you can read about [how to setup a crowdsale](https://www.ethereum.org/crowdsale) and start your own ICO!",
	url: "https://www.ethereum.org/token",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Tetrahedral Kites",
	description:
		"Apparently Alexander Graham Bell designed these really cool tetrahedral kites.",
	url:
		"http://publicdomainreview.org/collections/alexander-graham-bells-tetrahedral-kites-1903-9/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Game of Reich",
	description: "Make music with Conway's Game of Life.",
	url: "http://nexusosc.com/gameofreich/",
})

news.push({
	date: 1500080907000,
	tags: [],
	title: "Writing text on an oscilloscope",
	description: "A demo of writing text on an oscilloscope using Max for Live.",
	url: "https://www.youtube.com/watch?v=qBZoS8d2ov0",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Automatically Interactive Graphics",
	description:
		"A really cool graphics library that uses numerical derivatives to magically make procedurally generated graphics interactive!",
	url: "http://omrelli.ug/g9/gallery/",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Carbide Alpha",
	description:
		"A JavaScript programming environment that parses your code and creates interactive widgets.",
	url: "http://alpha.trycarbide.com/",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Why do game developers prefer Windows?",
	description:
		"An interesting history of computer graphics, how OpenGL fucked up, and why most computer games are made for Windows.",
	url:
		"https://softwareengineering.stackexchange.com/questions/60544/why-do-game-developers-prefer-windows",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Apollo Server 1.0",
	description: "A simple GraphQL backend for your next web project.",
	url:
		"https://dev-blog.apollodata.com/apollo-server-1-0-a-graphql-server-for-all-node-js-frameworks-2b37d3342f7c",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "GPU Accelerated JavaScript",
	description:
		"Convenient JavaScript interoperability with OpenGL graphics acceleration. I think soon we'll be seeing some relatively powerful machine learning models powered by JavaScript!",
	url: "https://github.com/gpujs/gpu.js",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Visual Programming Languages",
	description:
		"A curation of visual programming languages throughout the decades.",
	url:
		"http://blog.interfacevision.com/design/design-visual-progarmming-languages-snapshots/",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Minko - ShaderLab",
	description:
		"A really slick visual programming environment for graphics shaders.",
	url: "https://www.youtube.com/watch?v=yuR1e1PjU8Y",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Hidden messages in JavaScript property names",
	description:
		'An interesting exploit demonstrating the use of hidden unicode "code points". Whenever I read something like this, I think that a hacker is just someone who knows hundreds of random curiosities like this.',
	url:
		"https://www.stefanjudis.de/hidden-messages-in-javascript-property-names.html",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Gambler's Dice",
	description:
		"A simple project that simulates a die that obeys the gamblers fallacy.",
	url: "https://github.com/xori/gamblers-dice",
})

news.push({
	date: 1500752791000,
	tags: [],
	title: "Node-RED",
	description:
		"A visual programming environment for creating server applications for IoT, created by IBM.",
	url: "https://nodered.org/",
})

news.push({
	date: 1504757197000,
	tags: [],
	title: "Business Casual",
	url: "https://www.youtube.com/channel/UC_E4px0RST-qFwXLJWBav8Q",
	description:
		"A YouTube channel that explains the founding of many famous companies.",
})

news.push({
	date: 1504718660000,
	tags: [],
	title: "Chalktalk Magic Crayon Demo",
	url: "https://vimeo.com/232230096",
	description:
		"An interesting demo of an interactive drawing and simulation program.",
})

news.push({
	date: 1504199564000,
	tags: [],
	title: "Kyteman - Root Canal Therapy",
	url: "https://www.youtube.com/watch?v=_YbQwqBgdZA",
	description: "A song performed entirely on a modular synth.",
})

news.push({
	date: 1503987828000,
	tags: [],
	title: "Programming with Nothing by Tom Stuart",
	url: "https://www.youtube.com/watch?v=VUhlNx_-wYk",
	description:
		"A talk about lambda calculus and how you can write a program with only functions and no other primative datatypes.",
})

news.push({
	date: 1503987786000,
	tags: [],
	title: "Y Not - Adventures in Functional Programming by Jim Weirich",

	url: "https://www.youtube.com/watch?v=FITJMJjASUs",

	description: "A great explanation of the Y combinator from first principles.",
})

news.push({
	date: 1503256664000,
	tags: [],
	title: "Rebooting the Desktop Operating System Experience",
	url: "https://joshondesign.com/2017/08/18/idealos_essay",
	description:
		"An awesome essay on the lack of innovation in operating systems and some relatively straightforward features that would accelerate the software world.",
})

news.push({
	date: 1501222477000,
	tags: [],
	title: "The Evolution of Trust",
	url: "http://ncase.me/trust/",
	description: "An interactive explanation of the game theory of trust.",
})

news.push({
	date: 1511721999000,
	tags: [],
	title: "A History of Ideas",
	url:
		"http://www.bbc.co.uk/programmes/articles/3vVjcY47k2p5Wsnj3ZFHV5W/a-history-of-ideas",
	description: "The BBC produced a nice video series on philosophy.",
})

news.push({
	date: 1511739530295,
	tags: [],
	title: "You and your research",
	url: "http://www.paulgraham.com/hamming.html",
	description:
		"A talk given by Richard Hamming in 1986 about how to do great research.",
})

news.push({
	date: 1511739530295,
	tags: [],
	title: "Generominos: Ideation Cards for Interactive Art",
	url:
		"https://www.kickstarter.com/projects/1921765752/generominos-ideation-cards-for-interactive-art",
	description: "A creative game for coming up with creative ideas.",
})

news.push({
	date: 1511739530295,
	tags: [],
	title: "GuitarStack",
	url: "https://github.com/lucaong/guitarstack",
	description: "Guitar effects in your web browser using the Web Audio API!",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Bubble",
	url: "https://bubble.is/",
	description: "A graphical user interface for building web applications.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Augmenting Human Intellect",
	url: "http://www.1962paper.org/web.html",
	description:
		"The proposal Doug Engelbart submited to ARPA that culminated with the [Mother of all Demos](https://www.youtube.com/watch?v=1U-b7lxG_z8).",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "A Five Minutes Guide to Better Typography",
	url:
		"http://pierrickcalvez.com/journal/a-five-minutes-guide-to-better-typography",
	description: "",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Jam Origin: Midi Guitar 2",
	url: "http://www.jamorigin.com/",
	description: "This software can interpret your guitar as a MIDI controller!",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Snowflake Macro Photography",
	url:
		"https://chaoticmind75.blogspot.com/2013/08/my-technique-for-snowflakes-shooting.html",
	description: "An awesome guide to get you started with macro photography.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Why Does Time Exist at All?",
	url: "https://www.youtube.com/watch?time_continue=169&v=tqn73A5Csi0",
	description:
		"A mindblowing talk from a cosmologist about our existence in the universe.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Cosmo Project",
	url: "http://cosmoproject.github.io/about/",
	description: "A raspberry-pi based DIY audio pedal-box kit.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Sampulator",
	url: "http://sampulator.com/",
	description: "A fun music making application.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Compositor Lab",
	url: "https://compositor.io/lab/",
	description: "A UI for designing React components.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Computoser",
	url: "http://computoser.com/",
	description: "Computer generated music.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Pixelmator",
	url: "http://www.pixelmator.com/pro/",
	description: "An incredibly polished photo editing tool.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Microtonal Guitar",
	url: "https://www.youtube.com/watch?v=iRsSjh5TTqI",
	description: "A custom-built microtonal guitar.",
})

news.push({
	date: 1512489318405,
	tags: [],
	title: "Pedal Board",
	url: "https://github.com/DeerMichel/pedalboard",
	description: "Another webaudio guitar effects chain.",
})

export { news }

// 1512489318405
